services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      -  pgdb_volume:/var/lib/postgresql/data
      - ./containers/postgresql/init:/docker-entrypoint-initdb.d
    networks:
      - extsvcs
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80"
    networks:
      - extsvcs

volumes:
  pgdb_volume:
    external: true

networks:
  extsvcs:
    external: true
